### ISSUE TITLE
Find a way to use consuming app's eslint

### ISSUE THREAD

**Issue by IanVS** [BadgeLabs/mocha-eslint#13]
It is not ideal to include ESLint in this module's dependencies.  It should be up to the consuming app to decide what version of ESLint is used (after 0.17.0, which this module needs).  Peer dependencies seems designed for this task, but it seems to also cause a lot of other problems.  

Therefore, need to find some way of requiring ESLint to be installed without directly including it as a dependency.

**Comment by eagleeye** [comment]
First of all lets find why this does not work. I installed mocha-eslint with eslint-plugin-react plugin and everything works. So i suggest to close this issue until REAL problem will appear.

**Comment by IanVS** [comment]
The issue is that if I keep this module up-to-date with the latest eslint version, there may be projects which want to lock in to a particular version due to breaking changes. For example, 1.0.0 is fast approaching for ESLint, and it looks like default rules will be turned off unless they are opted into. 

My original intent for this module was to make it easy to add linting to mocha tests. For separation of concerns it would be best if choosing the version of ESLint is up to the end user. Ideally, I only want to change this module if/when the code of the module itself changes.

**Comment by dantman** [comment]
My thought was:
* Use peerDeps with a `>=` dictating the minimum version necessary.
** Dependents can use `^` in their own package to lock mocha to whatever major version they are known to be compatible with.
* When mocha makes a breaking change that changes the API necessary for mocha-eslint, release a new major version with an updated `>=`.
** As an optional extra you could also release a point release with a `<=` excluding the new major which is not compatible.

But what does peerDeps break? peerDeps are *supposed* to be designed for this task, trying to invent an alternative doesn't sound like good or smart idea.

**Comment by Turbo87** [comment]
@IanVS I also don't think that this is really an issue. If you add a specific `eslint` dependency in your project next to the `mocha-eslint` dependency npm shouldn't install another `eslint` package inside of `mocha-eslint`. Instead it will just use the explicitly installed `eslint` package instead.

the only thing that is necessary is keeping the `eslint` dependency of this package in a range where it is compatible with the ESLint API. so in practise that means: checking and updating for major version releases of ESLint, like the freshly released v2.0.0 (see #31).

**Comment by IanVS** [comment]
Thanks for the input.  I've decided to try to keep this module as dead simple as possible, and that means avoiding peerDependencies.  They are known to cause confusion, npm@3 does not install them automatically, and they're just generally a pain to deal with.  I don't really see the downside of just keeping this project abreast of ESLint breaking changes (with help from others like @Turbo87 when I get lazy :smiley_cat: ) and including eslint in the dependencies list.
