### ISSUE TITLE
Global installation of eslint can cause problems

### ISSUE THREAD

**Issue by IanVS** [BadgeLabs/mocha-eslint#17]
For example, if an older version of ESLint is installed on a user's machine, this module seems to default to using that version.  That can cause problems if a rule is configured which relies on the version of ESLint included in this package's dependencies.

**Comment by Turbo87** [comment]
I don't see why it would use the globally installed version. If this plugin would shell out to `eslint` this might be valid, but since it is using `require('eslint')` it should use the locally installed version instead.

**Comment by IanVS** [comment]
Yeah, not really sure why I made this issue.  I'm closing for now, and if someone has problems they can bring it up.
