### ISSUE TITLE
Update to ESLint 1.0.0

### ISSUE THREAD

**Issue by IanVS** [BadgeLabs/mocha-eslint#23]
This is a fairly major breaking change.  might be worth a bump to `1.0.0` on this package.  It would be nice to be able to stay in lock-step with ESLint as well.  Does anyone who is using this have any feedback or suggestions that would be good to implement now as part of the jump to 1.0?  Now is the time to make any other major changes to the API while we're at it.

**Comment by msimerson** [comment]
new user here, or attempted to be. But 1.0.0 support is required. It's time to jump...

**Comment by IanVS** [comment]
OK, I will do it tonight then.

**Comment by msimerson** [comment]
:+1:

**Comment by IanVS** [comment]
Please submit an issue if you try it out and have any troubles, or if you have any suggestions for improvement.  :smile:
