### ISSUE TITLE
Support for ESLint@2

### ISSUE THREAD

**Issue by Turbo87** [BadgeLabs/mocha-eslint#30]
As mentioned in #27 it would be desirable to support ESLint@2 as well. Unfortunately ESLint@2 currently seems to be limited to using npm@3 and it fails to work on the current test suite on Travis. I've prepared a branch with the necessary changes but it is blocked on https://github.com/eslint/eslint/issues/5241 for now.

**Comment by Turbo87** [comment]
As https://github.com/eslint/eslint/issues/5241 has mostly been resolved I've opened PR #31 now.

**Comment by thedark1337** [comment]
:+1: I'd love to see support for ESLint@2 added
