### ISSUE TITLE
Set '.' as default glob

### ISSUE THREAD

**Issue by piranna** [BadgeLabs/mocha-eslint#36]
Allow to don't need to set the globs array, using `.` (the current working directory) as starting point. This would allow to check all the project by default.

**Comment by IanVS** [comment]
I actually had this behavior at the beginning, but decided against it as being a bit too "magical".  Can you explain your use case of why this would be a worthwhile improvement?

**Comment by piranna** [comment]
Laziness is a valid use case? :-P I'm too much into default values and this seemed to me to be the obvious default behaviour, since probably this is the most common use case (analyce *everything* on this project).

**Comment by IanVS** [comment]
I see your point and agree that as a default it would make the most sense, but I don't want to add a default at all, preferring instead to require an explicit argument.  ESLint itself does not have a default either.  I think it's not too much work to configure.  ;)

**Comment by piranna** [comment]
Ok, it was mostly just a suggestion :-)
