### ISSUE TITLE
Report output is duplicated

### ISSUE THREAD

**Issue by piranna** [BadgeLabs/mocha-eslint#37]
By using the example on the README.md file I get the report output twice, one showing the files full paths and another showing only the relative ones to the root of the project.

**Comment by IanVS** [comment]
I just published a new version, `v2.0.2`, which should fix this bug.  Can you try it and let me know if it's working correctly?

**Comment by piranna** [comment]
Confirmed with `v2.0.2` ;-) Thanks! :-D
