### ISSUE TITLE
Release Current Master

### ISSUE THREAD

**Issue by EndangeredMassa** [BadgeLabs/mocha-eslint#42]
Can we get a new release with the new commits on master? Specifically, I would really like to be able to use https://github.com/BadgeLabs/mocha-eslint/commit/b69800983f1fa1036ab380cc165408a7b03cd799.

**Comment by IanVS** [comment]
Absolutely.  I'll do it tonight, thanks for the nudge.

**Comment by IanVS** [comment]
[2.1.0](https://github.com/BadgeLabs/mocha-eslint/releases/tag/v2.1.0) is released.
