### ISSUE TITLE
Comparison with eslint-plugin-mocha?

### ISSUE THREAD

**Issue by kristianmandrup** [BadgeLabs/mocha-eslint#49]
I found this [eslint-mocha-plugin](https://www.npmjs.com/package/eslint-plugin-mocha)

What are the pros/cons vs this one?

How the fuck do I lint my mocha tests with `eslint` !?!?!? I'm fucking lost! Been spending hours...
WTF! Javascript has become a nightmare! :O

**Comment by IanVS** [comment]
eslint-plugin-mocha adds a set of linting rules to ESLint that you can apply to your mocha files.  So, for instance, if you want to make sure all your tests have unique titles, you can turn on [mocha/no-identical-title](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-identical-title.md).  

So, this project is completely different from that one, and you can use both together if you like.

If you'd like more help setting up ESLint for your project, I'd suggest jumping into their gitter chat and asking questions there.  You'll likely get the best help that way.
