### ISSUE TITLE
More Customizable Output

### ISSUE THREAD

**Issue by adambullmer** [BadgeLabs/mocha-eslint#54]
I would like to propose either of the following:
- Add options for changing the Top level `describe` title
- Export the `index.js@test()` function for injecting into custom `describe` blocks

My use case is that I have authored a yeoman plugin, and want to lint the resulting scaffolded files. It would be nice to include those in a hierarchy that matches my testing hierarchy (sub/generator describes). I think ideally I would just be able to run test with a given file, mocking out the default module, but a customizable describe header would also be sufficient. Otherwise I see several `eslint` headers with no context of which module I was testing at the end of the output.

**Comment by IanVS** [comment]
Thanks for the idea.  Is your plugin open source?  I'd like to try it out a little to see if I can find a good way to do what you're asking for.  

Alternatively, would you be willing to take a shot at a PR?

**Comment by adambullmer** [comment]
Opened a PR with those changes. Let me know if you need/want any more to it 👍

**Comment by adambullmer** [comment]
IN answer to your other question, that open source project is https://github.com/adambullmer/generator-angular-bro
