### ISSUE TITLE
Support globbing

### ISSUE THREAD

**Issue by Globegitter** [BadgeLabs/mocha-eslint#6]
Another great thing to have would be globbing support (https://github.com/isaacs/node-glob) so you could add files/paths such as `tests/*.js` or any other patterns you want to filter for.

**Comment by IanVS** [comment]
Great idea.  Shouldn't be hard to do, the only question then becomes how to break up the mocha tests.  Does each file get its own test?  Or each glob pattern?  Right now, each provided path is a separate test which can pass or fail.  Will have to think about it.  Any suggestions?
