### ISSUE TITLE
mocha-eslint fails for BBD style in Mocha v6

### ISSUE THREAD

**Issue by ungrim97** [BadgeLabs/mocha-eslint#61]
Hi,

It would appear that the mocha-eslint test uses the TDD interface. This means that if the user is using any other interface then the test fails`ReferenceError: describe is not defined`

I think this is because of a change made for https://github.com/mochajs/mocha/commit/b5c0fb0a26ee9f8fd574e78732a2cf715d7ab6ca, though I don't know enough about the Mocha code to say for sure. If I understand correctly though this is due to the fact that Mocha used to always load the BDD interface regardless of the interface in use. I believe this will affect anyone using Mocha >= 6.0.0

Ideally either the mocha-eslint tests should provide an option for any interface

`node_modules/mocha/bin/mocha --ui tdd test/eslint.test.js`
```
const lintTest = require('mocha-eslint');
 
lintTest(['bin', 'src', 'test'], {
  strict: true,                                                                                                                     
  formatter: 'tap',
  timeout: 0
});
```

Yours,
Mike E

**Comment by IanVS** [comment]
Hi, thanks for bringing this up.  Would you be willing to submit a PR to fix this?  It's unlikely I'll be able to get to it.

**Comment by ungrim97** [comment]
Hi

I can certainly give it a go though no promises. I suspect the easiest 
thing would be to specifically import the functions from mocha. Will see 
what I can do

Mike

**Comment by IanVS** [comment]
Thanks!
